language: go
go:
  - "1.9"

services:
  - docker

install:
  - go get -u golang.org/x/tools/...
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/golang/dep/cmd/dep
  - make deps

script:
  - make check

notifications:
  email: false

